name: Merge Dev to Testing on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  test:
    if: |
      github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          cd src
          python -m pytest addition.py

  merge-to-testing:
    if: |
      github.event.pull_request.merged == true 
     
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "rana.ritik9639@gmail.com"
          git config --global user.name "rana7862"

      - name: Merge development into testing
        run: |
          git fetch origin development
          git checkout testing
          git merge origin/development --no-edit
          git push origin testing
  script:
    if: |
      github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Run custom script
        run: |
          sudo chmod +x ./script.sh
          bash script.sh create_new_release
  macos:
    if: |
      github.event.pull_request.merged == true 
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: prepare package root
        run: |
          mkdir -p ./pkg-root/usr/local/bin
          cp src/addition.py ./pkg-root/usr/local/bin/addition
          cp script.sh ./pkg-root/usr/local/bin/myscript
          chmod +x ./pkg-root/usr/local/bin/addition ./pkg-root/usr/local/bin/myscript

      - name: build pkg
        run: |
          VERSION=$(cut -d'=' -f2 ./releaseNo.env)
          pkgbuild --root ./pkg-root --identifier com.github.ritik.githubprac --version $VERSION --install-location "/" MYAPP.pkg

        
      - name: Upload pkg
        uses: actions/upload-artifact@v4
        with:
          name: macos-pkg
          path: MYAPP.pkg



